# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  pw-focal-development:
    docker:
      - image: mcr.microsoft.com/playwright:v1.27.1-focal
    environment:
      NODE_ENV: development

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14.6.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: yarn test
          command: yarn test
