# # Use the latest 2.1 version of CircleCI pipeline process engine.
# # See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@5.0.3

jobs:
  setup:
    executor:
      name: node/default
      tag: '14.17.0'
    steps:
      - checkout
      - run:
          command: yarn install
          name: Installing deps
      - run:
          command: npx playwright install
          name: installing playwright
      - run:
          command: yarn start
          name: Building apps
  test:
    executor:
      name: node/default
      tag: '14.17.0'
    docker:
      - image: mcr.microsoft.com/playwright:v1.27.1-focal
    steps:
      - checkout
      - run:
          name: Download dependency
          command: npm ci
      - run:
          name: Installing dependency
          command: yarn install
      - run:
          name: Building apps
          command: yarn build
      - run:
          name: Run tests
          command: yarn test
      - store_test_results:
          path: results.xml

workflows:
  test_my_app:
    jobs:
      - setup