# # Use the latest 2.1 version of CircleCI pipeline process engine.
# # See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@5.0.3

jobs:
  build:
    executor:
      name: node/default
      tag: '14.17.0'
    docker:
      - image: mcr.microsoft.com/playwright:v1.27.1-focal
    steps:
      - checkout
      # look for existing cache and restore if found
      - restore_cache:
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Installing dependency
          command: yarn install
      - run:
          name: Building apps
          command: yarn build
      # Save workspace for next step
      - persist_to_workspace:
          root: ~/
          paths:
            - "project"
  test1:
    executor:
      name: node/default
      tag: '14.17.0'
    docker:
      - image: mcr.microsoft.com/playwright:v1.27.1-focal
    steps:
      - checkout
      # Get workspace from previous step
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests
          command: yarn test
      # save any changes to the cache
      - save_cache:
          paths:
            - ./node_modules
            - ./.next/cache
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
  test:
    docker:
      - image: cimg/base:2022.03
    steps:
      - run: echo "TEST 2 Passed"
  deploy:
    executor:
      name: node/default
      tag: '14.17.0'
    docker:
      - image: mcr.microsoft.com/playwright:v1.27.1-focal
    steps:
      - checkout
      - run:
          name: Deploy {{ .Branch }} branch to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git

workflows:
  test_and_deploy:
    jobs:
      - build
      - test1:
          requires:
            - build
      - deploy:
          requires:
            - test1
          filters:
            branches:
              only: main